version: "3.8"
services:
  # Mysql database container
  db:
    image: mysql
    container_name: promotions_engine_db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - promotions_engine

  # phpmyadmin container
  phpmyadmin:
    image: phpmyadmin
    container_name: promotions_engine_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - promotions_engine

  # Symfony apache project container
  www:
    build: docker/php
    container_name: promotions_engine_php
    ports:
      - "8742:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - promotions_engine

  redis:
    image: redis:7.0.0
    container_name: promotions_engine_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - promotions_engine

networks:
  promotions_engine:

volumes:
  db-data:
